apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Values.app.name }}-hpa"
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{ .Values.app.name }}
  minReplicas: {{ .Values.deployment.replicaSet.min }}
  maxReplicas: {{ .Values.deployment.replicaSet.max }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
         type: Utilization
         averageUtilization: {{ .Values.deployment.hpa.targetCPUUtilization }}
  - type: Resource
    resource:
      name: memory
      target:
         type: Utilization
         averageUtilization: {{ .Values.deployment.hpa.targetMemoryUtilization }}