apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-nginx
  labels:
   app: {{ .Values.app.name }}
  annotations:
    kubernetes.io/ingress.class: nginx-http-test
spec:
  rules:
   - host: {{ .Values.app.service.dns.ingressHostname }}
     http:
      paths:
        - backend:
            service: 
              name: {{ .Values.app.name }}-ingress
              port: 
                 number: 9090
              path: {{ .Values.app.service.path }}
              pathType: Prefix