apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "{{ .Values.app.name }}-pdb"
  namespace: {{ .Values.deployment.environment }} 
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}  # Minimum number of pods that must be available during disruptions
  selector:
    matchLabels:
      app: {{ .Values.app.name }}