apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service.env.ServiceAccountName }}
  namespace : {{ .Values.environment }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Values.app.name }}-namespace-reader"
  namespace : {{ .Values.environment }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Values.app.name }}-role-binding"
subjects:
- kind: ServiceAccount
  name: {{ .Values.service.env.ServiceAccountName }}
roleRef:
  kind: Role
  name: "{{ .Values.app.name }}-namespace-reader"
  apiGroup: rbac.authorization.k8s.io